name: Frontend Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_baseUrl: 'https://deploy-preview-${{ github.event.number }}--tender-stonebraker-78d2e4.netlify.app'
        with:
          wait-on: 'https://deploy-preview-${{ github.event.number }}--tender-stonebraker-78d2e4.netlify.app'
          wait-on-timeout: 90
